const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Behaviors.Anchor,
		C3.Plugins.Text,
		C3.Plugins.GamePush_Channels,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.Tilemap,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerGet,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerAdd,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSet,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{Color: 0},
	{PX: 0},
	{PY: 0},
	{PUid: 0},
	{IsMatch: 0},
	{ID: 0},
	{rafaeltrigo: 0},
	{Якорь: 0},
	{Spawner: 0},
	{Sprite: 0},
	{Mask: 0},
	{Debugrafaeltrigo: 0},
	{Points: 0},
	{GamePushChannels: 0},
	{GamePush: 0},
	{Текст: 0},
	{КартаТайлов: 0},
	{btnclose_n: 0},
	{btnforew_n: 0},
	{FramePick: 0},
	{XPlayer: 0},
	{YPlayer: 0},
	{UId: 0},
	{CallChecks: 0},
	{DistanceXY: 0},
	{Money: 0},
	{Frame: 0},
	{XRafa: 0},
	{YRafa: 0},
	{RafaUID: 0},
	{Parameter0: 0},
	{Parameter1: 0},
	{Parameter2: 0},
	{Parameter3: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	rafaeltrigo: class extends self.ISpriteInstance {},
	Spawner: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Mask: class extends self.ISpriteInstance {},
	Debugrafaeltrigo: class extends self.ITextInstance {},
	Points: class extends self.ITextInstance {},
	GamePushChannels: class extends self.IInstance {},
	GamePush: class extends self.IInstance {},
	Текст: class extends self.ITextInstance {},
	КартаТайлов: class extends self.ITilemapInstance {},
	btnclose_n: class extends self.ISpriteInstance {},
	btnforew_n: class extends self.ISpriteInstance {}
}